[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
ads1x1x = "0.2.2"
colored = "2.0.0"
embedded-hal = "0.2.7"
nb = "1.0.0"
rppal = { version = "0.13.1", features = ["hal"] }
rusb = { version = "0.9.1", features = ["vendored"] }
serialport = "4.2.0"
