name: Build tester

on:
  push:
    paths:
      - .github/workflows/build-tester.yml
      - tester/**
      - Cargo*
      - rust*
      - .cargo/**

jobs:
  # Written in Rust
  build-tester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: aarch64-unknown-linux-gnu

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "aarch64-unknown-linux-gnu"

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu

      - uses: actions/upload-artifact@v2
        with:
          name: tester
          path: target/aarch64-unknown-linux-gnu/release/tester
