name: Build backend

on:
  push:
    paths:
      - .github/workflows/build-backend.yml
      - backend/**
      - package*.json\

jobs:

  # Written in Node.JS, built as a Docker image
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: backend
          push: true
          tags: thedevminertv/slimevr-testing-jig-backend:latest
